POST http://localhost:3001/catalogo_servidor
    Content-Type: application/json

{
    "nombre":"",
    "ipdireccion":"",
    "tipo":""

}


###

POST http://localhost:3002/catalogo_servidor
Content-Type: application/json

{
    "id":"700",
    "nombre":"asdf1"
}

###

GET http://localhost:3002/catalogo_servidor/300


###

DELETE http://localhost:3002/catalogo_servidor/300

###

PUT http://localhost:3002/catalogo_servidor/700
Content-Type: application/json

{
    "nombre":"cuca"
}



########################################
#CATALOGO SERVICIO#
########################################
GET http://localhost:3001/catalogo_servicio



########################################
#CATALOGO DETALLE SERVIDOR#
########################################
GET http://localhost:3001/catalogo_detalleservidor/6